### ISSUE TITLE
python fails on Libre aml-s905x-cc

### ISSUE THREAD

**Issue by ilostmymindcom** [pablobuenaposada/HonDash#259]
When I run "make virtualenv"
I get:
npm install

up to date, audited 11 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
python3.9 -m venv venv
make: python3.9: No such file or directory
make: *** [Makefile:51: venv] Error 127

The hardware is a Libre Computer aml-s905x-cc running Raspbian 12 from https://distro.libre.computer/ci/raspbian/12/2023-10-10-raspbian-bookworm-arm64%2Baml-s905x-cc.img.xz
I have a raspberry pi coming, I just figured I could get it working on this real quick.

**Comment by ilostmymindcom** [comment]
I was following the instruction line for line, but here is the results:
honda@raspbian-bookworm-aml-s905x-cc:~/Desktop/HonDash $ sudo make system_dependencies
apt install --yes --no-install-recommends libatlas-base-dev libsnappy-dev npm python3-pandas
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libatlas-base-dev is already the newest version (3.10.3-13).
libsnappy-dev is already the newest version (1.1.9-3).
npm is already the newest version (9.2.0~ds1-1).
python3-pandas is already the newest version (1.5.3+dfsg-2).
The following packages were automatically installed and are no longer required:
  gtk2-engines-clearlookspix libcamera-apps libcamera0.1 libpisp0.0.1
  librtimulib-dev libssl1.1 libwpe-1.0-1 libwpebackend-fdo-1.0-1
  linux-kbuild-6.1 python3-sense-hat
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
honda@raspbian-bookworm-aml-s905x-cc:~/Desktop/HonDash $ sudo make virtualenv
npm install

up to date, audited 11 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
python3.9 -m venv venv
make: python3.9: No such file or directory
make: *** [Makefile:51: venv] Error 127
honda@raspbian-bookworm-aml-s905x-cc:~/Desktop/HonDash $ python
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
I have python 3.11.2 from the looks of it, so I'm wondering if something is hard coded to look for 3.9, instead of just using python3.

**Comment by pablobuenaposada** [comment]
yes, it is hardcoded to use python 3.9, if you want to use another system just make python3.9 available

**Comment by pablobuenaposada** [comment]
no updates so closing this
