### ISSUE TITLE
Can you make a README with a set of instructions on how to get it setup?

### ISSUE THREAD

**Issue by ssphon** [pablobuenaposada/HonDash#260]
Such as Docker installation, Raspberry Pi download, etc

What we need to do to get setup

**Comment by pablobuenaposada** [comment]
you mean this?
https://hondash.com/SOFTWARE.html
https://github.com/pablobuenaposada/HonDash/tree/master/src#readme

**Comment by LarryChiem** [comment]
@pablobuenaposada it's not really detailed. If you're a user on windows, maybe a beginner to Docker or whatever, it's not clear what do to step by step.

[m/pablobuenaposada/HonDash/tree/master/src#readme](https://github.com/pablobuenaposada/HonDash/tree/master/src#readme)
For example,the first thing it says is:

> With Docker
> for the first time:
> 
> make docker/system_dependencies
Where are we supposed to download Docker? Does it matter if we are on windows or mac? Where do we run this `make docker/system_dependencies` command?

**Comment by pablobuenaposada** [comment]
I am confused, are you trying to developer a new feature or just have it running in raspberry pi? of course these advance installation instructions suppose you have a bit of context about docker and couple of things more, that of course are not explained because is not the goal of this project.
