### ISSUE TITLE
Fuel level 

### ISSUE THREAD

**Issue by Eman4509** [pablobuenaposada/HonDash#262]
Just got the hondash setup all done in my car using raspberry pi 4b and hondata s300. Trying to get the fuel level figured out. Set everything up as 3.31 and .17 on the hondash and hondata and when the car is running it shows 50% with a full tank but with the key to just the on position it reads 98-100% like it should. Adjusted the 3.31 to 5v and its up to 70% while running but I can't go any higher then 5v correct? Wired it all like direction said with resistor.

**Comment by pablobuenaposada** [comment]
first start by confirming that in kpro works, later you can set it up in hondash

**Comment by Eman4509** [comment]
I have s manager. And it doesn't allow you to use a comma as the decimal could that have anything to do with it?

**Comment by pablobuenaposada** [comment]
kmanager or smanager, doesn't matter, configure it there first and confirm that it works here.

**Comment by pablobuenaposada** [comment]
no updates and I think this is a issue down in s manager so for now closing this
