### ISSUE TITLE
Error: zlmdb 19.9.3 has requirement numpy==1.15.4

### ISSUE THREAD

**Issue by AndreMiras** [pablobuenaposada/HonDash#81]
When building the virtualenv we get the following (silent) error:
```
ERROR: zlmdb 19.9.3 has requirement numpy==1.15.4, but you'll have numpy 1.17.2 which is incompatible.
```
This was introduced in: 0c416f79bbe6e17c063d0795f217ecd64d70b17d

**Comment by pablobuenaposada** [comment]
this is not happening anymore, closing
